version: '3'

services:
  mongo:
    image: 'mongo:4.2'
    ports:
      - '17017:27017'
    command: mongod
  app:
    depends_on:
      - mongo
    image: 'wikanyaa/express-demo'
    ports:
      - '3005:3000'
    command: 'npm run dev'
